#!/usr/bin/python3.10
'''
fo=open("with_loop.txt","r")
data=(fo.readline())
fo.close()
print(data)
'''
'''
fo=open("with_loop.txt","r")
data=fo.readlines()
fo.close()
print(data)
'''
fo=open("with_loop.txt","r")
data=fo.readlines()
fo.close()
'''
for each in range(3):
    print(data[each]
'''
print(data[-1])
